using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PlaytimeShare;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferWindow : FancyWindow
{
    public TimeTransferWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
