- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

- type: chameleonOutfit
  id: CluwneChameleonOutfit
  name: job-title-cluwne
  startingGear: CluwneGear
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesBlindfold
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
