using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PlaytimeShare.Helpers;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferServerListingControl : Control
{
    public TimeTransferServerListingControl(string name, string publicKey, bool enabled)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = name;
        PublicKeyLabel.Text = publicKey;
        EnabledLabel.Text = enabled.ToString();
    }
}

