using Content.Client.PlaytimeShare.Helpers;
using Content.Shared.PlaytimeShare;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.PlaytimeShare.TimeTransferAdmin;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferServerViewControl : Control
{
    public void HandleState(TimeTransferAdminState state)
    {
        AddServerListings(state);
    }

    private void AddServerListings(TimeTransferAdminState state)
    {
        ServerListingContainer.RemoveAllChildren();

        ServerListingContainer.AddChild(new Button
        {
            Text = "Add Server",
        });

        foreach (var server in state.TrustedServers)
        {
            var listing = new TimeTransferServerListingControl(server.ServerName, server.ServerPublicKey, server.Enabled);
            listing.DeleteButton.OnPressed += _ => DeleteServerListing(server);
            listing.EditButton.OnPressed += _ => EditServerListing(server);

            ServerListingContainer.AddChild(new TimeTransferServerListingControl(server.ServerName, server.ServerPublicKey, server.Enabled));
        }
    }

    private void EditServerListing(TimeTransferServerInfoSerializable serverInfo)
    {

    }

    private void DeleteServerListing(TimeTransferServerInfoSerializable serverInfo)
    {

    }

    // Load edit function
}
