using Content.Client.UserInterface.Controls;
using Content.Shared.PlaytimeShare;
using Robust.Client.AutoGenerated;

namespace Content.Client.PlaytimeShare.TimeTransferAdmin;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferAdminWindow : FancyWindow
{
    public void HandleState(TimeTransferAdminState state)
    {

    }
}
