using Content.Shared.PlaytimeShare;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.PlaytimeShare.TimeTransferAdmin;

[GenerateTypedNameReferences]
public sealed partial class TimeTransfersTransfersControl : Control
{
    public void HandleState(TimeTransferAdminState state)
    {

    }
}
